[features]
seeds = false
skip-lint = false
[programs.localnet]
crud_contract = "coUnmi3oBUtwtd9fjeAvSsJssXh5A5xyPbhpewyzRVF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/androidrighthand/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
